### ISSUE TITLE
Donate fededp/Pigeon to falcosecurity

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/evolution#251]
**Repository**:  

https://github.com/FedeDP/Pigeon

**Motivation**

In test-infra, peribolos is not capable of setting secrets and variables for github actions.
We (me, @jasondellaluce and @cappellinsamuele) developed a small golang tool to helps us with that.
Basically, it takes a yaml conf, much similar to the [org.yaml](https://github.com/falcosecurity/test-infra/blob/master/config/org.yaml) one used by test-infra. 
Idea is to let this new tool be used inside test-infra to setup per-org/repo github actions variables and secrets (where secrets are stored on 1password and thus not written in configuration file).

Example configuration:
```yaml
orgs:
  foo:
    actions:
      variables:
        orgVar1: "orgValue1"
      secrets:
        - orgSecret0
    repos:
      bar:
        actions:
          variables:
            repoVar1: "repoValue1"
            repoVar2: "repoValue2"
          secrets:
            - repoSecret0
```

Notable: as part of the effort, a PR on `go-github` (google github's API go client library) was created and successfully merged, to expose new gha variables API: https://github.com/google/go-github/pull/2652
